apps/user/urls.py
from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from .views import RegisterView, ProfileView, LogoutAPIView, verify_email

app_name = 'user'

urlpatterns = [

    path("signup/", RegisterView.as_view(), name="signup"),

    path('verify/', verify_email, name='verify_email'),
    # POST /api/users/login/ -> 로그인
    path("login/", TokenObtainPairView.as_view(), name="login"),
    # POST /api/users/login/ -> 로그아웃
    path("logout/", LogoutAPIView.as_view(), name="logout"),
    # GET /api/users/profile/ -> 내 프로필 조회
    # PATCH /api/users/me/ -> 내 프로필 수정
    path('profile/', ProfileView.as_view(), name="profile"),

    # JWT
    path('token', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify', TokenVerifyView.as_view(), name='token_verify'),

]

templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pystagram</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'font-awesome/css/fontawesome.css' %}" rel="stylesheet" />
    <link href="{% static 'font-awesome/css/brands.css' %}" rel="stylesheet" />
    <link href="{% static 'font-awesome/css/solid.css' %}" rel="stylesheet" />
    <link href="{% static 'css/my_style.css' %}" rel="stylesheet" />
    {% block style %}{% endblock %}
</head>
<body>
<nav class="d-flex justify-content-between py-2 px-4 bg-black text-white">
    <div>
        <a href="{% url 'main' %}" class="text-decoration-none text-white">oz_bank</a>
    </div>
    <div>
{#        <a href="{% url 'search' %}">#}
{#            <i class="fa-solid fa-magnifying-glass text-white"></i>#}
{#        </a>#}
    </div>
    <div class="text-end">
        {% if request.user.is_authenticated %}
            {{ request.user.nickname }}
            <form action="{% url 'user:logout' %}" method="post" class="d-inline ms-2">
                {%  csrf_token %}
                <button class="btn btn-dark btn-sm">로그아웃</button>
            </form>
        {% else %}
            <a class="btn btn-dark btn-sm" href="{% url 'user:signup' %}">회원가입</a>
            <a class="btn btn-dark btn-sm" href="{% url 'user:login' %}">로그인</a>
        {% endif %}
    </div>
</nav>

<div class="container pt-3">
    {% block content %}{% endblock %}
</div>

    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>